name: linux build tachyon_engine

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          submodules: recursive
          run: |
            echo "The ${{ github.repository }} repository has been cloned to the runner."
            echo "Current working directory"
            pwd
            echo "Files detected by git"
            git ls-files

      - run: echo "Checking submodules actually contain files"
      - name: submodule setup
        run: tree external -L 2

      - name: xmake setup
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: xmake build
        run: xmake build --yes --verbose tachyon_engine
