name: linux build tachyon_engine

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: pre-flight checks
        shell: bash
        run: echo "Current working directory:"
        run: pwd
        run: echo "Files detected by git"
        run: git ls-files

      - name: Check out repository code
        uses: actions/checkout@v5
        shell: bash
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
        run: echo "Current working directory"
        run: pwd
        run: echo "Files detected by git"
        run: git ls-files

      - name: submodule setup
        shell: bash
        run: echo "Checking submodules actually contain files"
        run: tree external -L 2

      - name: xmake setup
        shell: bash
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: xmake build
        shell: bash
        run: xmake build --yes --verbose tachyon_engine
